name: Tourism_MLOps_Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:   # allow manual trigger

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install xgboost==1.7.5
        pip install huggingface_hub

    - name: Run data ingestion + preprocessing + modeling
      run: |
        python tourism_project/data_ingestion.py
        python tourism_project/preprocessing.py
        python tourism_project/model_building.py
        python tourism_project/model_tuning.py
        python tourism_project/finalize_model.py

    - name: Upload artifacts to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: trained_models
        path: tourism_project/artifacts/

    - name: Push final model to HuggingFace Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python tourism_project/push_to_hf.py
